### ISSUE TITLE
一个任务还没执行完成爬虫就退出？

### ISSUE THREAD

**Issue by xmnsl** [zhshch2002/goribot#12]
`
package main

import (
	"fmt"
	"github.com/zhshch2002/goribot"
	"crawlab/service/babyTree/parser"
)

func main() {
	s := goribot.NewSpider(
		//goribot.Limiter(
		//	true,
		//	&goribot.LimitRule{
		//		Glob:        "*.babytree.com",
		//		Allow:       goribot.Allow,
		//		Rate:        2,
		//		//Delay:       5 * time.Second,
		//		RandomDelay: 5 * time.Second,
		//		Parallelism: 3,
		//		MaxReq:      3,
		//		MaxDepth: 5,
		//	},
		//),
		goribot.SetDepthFirst(true),
		goribot.RefererFiller(),
		goribot.RandomUserAgent(),
		goribot.SpiderLogPrint(),
	)

	s.AddTask(
		goribot.Get("http://www.babytree.com/difang/allCities.php"),
		parser.CityList,
	)

	s.OnItem(func(i interface{}) interface{} {
		fmt.Printf("Item : %+v\r\n",i)
		return i
	})

	s.Run()
}
`
`
package parser

import (
	"fmt"
	"github.com/PuerkitoBio/goquery"
	"github.com/zhshch2002/goribot"
	"crawlab/models"
	"net/url"
	"strings"
)

func CityList(ctx *goribot.Context){
	if ctx.Resp.Dom != nil {
		cityList := make([]map[string]string, 2)
		cityList[0] = map[string]string{"city": "北京", "py": "beijing"}
		cityList[1] = map[string]string{"city": "上海", "py": "shanghai"}

		ctx.Resp.Dom.Find("a").Each(func(i int, sel *goquery.Selection) {
			href, exists := sel.Attr("href")
			index := strings.LastIndex(href, "?location=")
			if index == -1 && exists {
				u, _ := url.Parse(href)
				i2 := strings.Index(u.Host, ".")
				u2 := u.Host[:i2]
				i3 := strings.Index(u2, "-city")
				if i3 > -1 {
					py := u2[:i3]
					cityList = append(cityList, map[string]string{"city": sel.Text(), "py": py})
				}
			}
		})
		fmt.Printf("city Lists : %+v\r\n",cityList)
		for _, c := range cityList {
			py := c["py"]
			uri := "http://www.babytree.com/community/" + py + "/index_1.html#topicpos"
			ctx.AddItem(models.CityList{py,uri})
		}
	}
}
`
这是执行打印的结果：
![image](https://user-images.githubusercontent.com/44631130/84867855-64ca5080-b0ae-11ea-9313-f0c94576f9e6.png)

![image](https://user-images.githubusercontent.com/44631130/84867814-53814400-b0ae-11ea-873c-456ec632ee77.png)

为什么map内的Item无法全部打印出来？run方法就退出了？

**Comment by zhshch2002** [comment]
这是调度器的一个问题，把spider的AutoStop设置为false，再在run之后select{}就能完全执行。

我从goribot切出去一个 https://github.com/zhshch2002/gospider 没有这个问题。
