### ISSUE TITLE
http.Header has no field or method Clone

### ISSUE THREAD

**Issue by ariagecheney** [zhshch2002/goribot#2]
github.com\zhshch2002\goribot\net.go:61:32: r.Header.Clone undefined (type http.Header has no field or method Clone)

**Comment by zhshch2002** [comment]
I am not sure what the specific operation caused this error.What did you execute?

**Comment by 0x5e** [comment]
this method requires go 1.13.
https://golang.org/pkg/net/http/#Header.Clone

**Comment by laozhizi** [comment]
In older version, which is method replace Header.Clone?

**Comment by zhshch2002** [comment]
@laozhizi It's in `net.go` line 102 , method `goribot.Download`

**Comment by laozhizi** [comment]
> @laozhizi It's in `net.go` line 102 , method `goribot.Download`

ok, I got it
