### ISSUE TITLE
建议：自动处理 cookie

### ISSUE THREAD

**Issue by everyx** [zhshch2002/goribot#3]
当前貌似不能自动处理 cookie 的保存和发送，每次都需要手动设置 cookie 值，能否第一次任务设置 cookie 之后，自动处理呢？

**Comment by zhshch2002** [comment]
指的是Cookie Jar的功能吗？Cookie Jar在v0.1.4已经添加上了。可以尝试`go get -u github.com/zhshch2002/goribot`更新一下。

**Comment by everyx** [comment]
@zhshch2002 没在文档中看到，能给一下文档的链接么？谢谢

**Comment by everyx** [comment]
我更新了貌似还是不行，我想要的是第一次加入 task 的时候设置好初始的 cookie，后续会自动使用这个 cookie 到后面每一次连接中，但是好像还不行。

首次的 task 如下，
```golang
goribot.GetReq(importerSearchEndpoint).
		SetParam(importerSearchParam).
		AddCookie(&cookie)
s.AddTask(task, importerSearch)
```

然后，后续只需要
```golang
goribot.GetReq(importerSearchEndpoint).
		SetParam(importerSearchParam)
ctx.AddTask(task, importerSearch)
```
而不用重新设置 cookie

**Comment by zhshch2002** [comment]
我明白了，你是要给所有的请求加一样的Cookie？

你何以写一个扩展，在OnAdd回调的时候添加Cookie。

```go
s := goribot.NewSpider()
s.Use(func(s *goribot.Spider) {
	s.OnAdd(func(ctx *goribot.Context, t *goribot.Task) *goribot.Task {
		t.Request.AddCookie((&cookie))
	})
})
```
这样由爬虫发起的所有请求就都带有你设置的一个Cookie了。

我说的Cookie Jar是在服务器设置Cookie后自动存储用的，不是在蜘蛛上的外部设置功能。

**Comment by zhshch2002** [comment]
我以为是 Cookie Jar 没有正常工作呢😂

**Comment by everyx** [comment]
是的，既然有了 Cookie Jar，是否考虑加上这个功能呢？这里初始传入的 cookie 实际也是服务器返回的，只不过不是在 goribot 中请求服务器返回的（因为有验证码，所以我手动登录取了这个值），然后在 goribot 可以像对待服务器的 set-cookie header 一样，把初始的这个 cookie 也加进来。

每次加入 task 时，可以从上一次请求的 request 中取到这些 cookie，并设置

**Comment by zhshch2002** [comment]
谢谢建议，今天早上完成了你说的功能。可能需要你再更新下一下本地的版本到v0.1.5。

参见文档 [https://goribot.imagician.net/extensions.html#addcookietojar-%E5%90%91-cookie-jar-%E6%B7%BB%E5%8A%A0-cookie](https://goribot.imagician.net/extensions.html#addcookietojar-%E5%90%91-cookie-jar-%E6%B7%BB%E5%8A%A0-cookie)
