### ISSUE TITLE
请教一个关于爬取结果存储的问题

### ISSUE THREAD

**Issue by LakeVilladom** [zhshch2002/goribot#6]
代码结构如下：
```go
func main() {
	...
	s.AddTask(goribot.GetReq(url), f1)
	s.Run()
}

var f1 = func(ctx *goribot.Context) {
	...
        url:= ctx.Resp.Json("url").Int()
	file_name := ctx.Resp.Json("file_name").Int()
	file_size := ctx.Resp.Json("file_size").Int()
	ctx.AddTask(goribot.GetReq(url),f2)
}

var f2 = func(ctx *goribot.Context) {
	file_download_url := ctx.Resp.Json("file_download_url")
}
```

> f1中获取的`file_name`、`file_size`、和f2中获取的`file_download_url ` ，如何能让这三个字段同时整体输出

**Comment by zhshch2002** [comment]
goribot.GetReq的时候可以设置Meta参数，然后在下一个ctx里取出来再输出就行了

**Comment by LakeVilladom** [comment]
非常感谢，这个问题昨天搞定了，刚开始我是发现在Context中有Meta字段，所以通过ctx.Meta["A"]="A"，然后再下一个ctx 通过ctx.Meta["A"]取得，发现取不到，后来发现Request中也有Meta字段，然后就通过WithMeta() 搞定了  这儿有个疑问，这个参数必须通过Request请求携带，然后返回给Response这种方式吗  这样会不会增加Request请求开销

**Comment by LakeVilladom** [comment]
另外我在写另外一个爬虫，大致如下：
   post登录系统，然后返回json格式的数据，获取到token，然后后续爬取内容的请求的Header都要携带这个token。

每次get或者post都要通过`.WithMeta("Authorization", token)`来携带 token，又麻烦又不优雅，然后我发现`Spider.OnReq(）`这个方法，接下来我的思路是写两个爬虫s1  s2  ,s1获取token 然后s2.OnReq()设置req携带token
```go
	s2.OnReq(func(ctx *goribot.Context, req *goribot.Request) *goribot.Request {
		req.WithMeta("Authorization", token)
		return req
	})
```
 现在发现爬取都会报错，提示缺少令牌（没有这样改进前爬取是可以的）

现在我的疑问是：1、这样写是否合适，如果合适我再排查报错原因
                             2、有无更加优雅的方法

**Comment by LakeVilladom** [comment]
> 另外我在写另外一个爬虫，大致如下：
> post登录系统，然后返回json格式的数据，获取到token，然后后续爬取内容的请求的Header都要携带这个token。
> 
> 每次get或者post都要通过`.WithMeta("Authorization", token)`来携带 token，又麻烦又不优雅，然后我发现`Spider.OnReq(）`这个方法，接下来我的思路是写两个爬虫s1 s2 ,s1获取token 然后s2.OnReq()设置req携带token
> 
> ```go
> 	s2.OnReq(func(ctx *goribot.Context, req *goribot.Request) *goribot.Request {
> 		req.WithMeta("Authorization", token)
> 		return req
> 	})
> ```
> 
> 现在发现爬取都会报错，提示缺少令牌（没有这样改进前爬取是可以的）
> 
> 现在我的疑问是：1、这样写是否合适，如果合适我再排查报错原因
> 2、有无更加优雅的方法


报错问题解决了，应该是`req.SetHeader("Authorization", token)`

**Comment by zhshch2002** [comment]
Meta只是在本地里传个数，不涉及网络操作。

还有别的问题吗？

**Comment by LakeVilladom** [comment]
越玩越有趣，现在能不能对PostFormReq  PostRawReq  PostJsonReq 的使用方法再来个案列说明，尤其PostRawReq

**Comment by zhshch2002** [comment]
其实我也没什么可特别介绍的，基本都是对标准库http的包装。具体可以看源码和这几个

- https://blog.csdn.net/mofiu/article/details/79925994
- https://golangnote.com/topic/246.html
