### ISSUE TITLE
feature request: 增加 func (s *Request)  AddParams(params string[string]) *Request

### ISSUE THREAD

**Issue by everyx** [zhshch2002/goribot#9]
每次增加多个 param 的时候要写不少次，用 map 一次搞定

```golang
func (s *Request)  AddParams(params string[string]) *Request
```

其他的 `AddCookie(s)`  `SetHeader(s)` `WithMeta(s)` 也可以这样做

**Comment by zhshch2002** [comment]
https://github.com/zhshch2002/gospider 和 https://github.com/zhshch2002/goreq 已经采纳了这个建议。十分感谢。新的蜘蛛应用的开发还请使用gospider。
